### ISSUE TITLE
Failing tests on pricing branch

### ISSUE THREAD

**Issue by iampersistent** [vespolina/core#18]
There are failing tests on the pricing branch that are failing because they need to be implement. Just communicate in the comment which tests you are working on to implement to avoid duplication of work.

**Comment by cordoval** [comment]
what is the relation between refactor and pricing? sorry i did not get that very clear, as the tests you are asking are for pricing right?

**Comment by iampersistent** [comment]
pricing is forked from refactor. the refactor does have a failing test that I need to look at, unless someone else looks at it first :)

**Comment by cordoval** [comment]
close in favor of #20
