### ISSUE TITLE
Refactor getPayment/setPayment

### ISSUE THREAD

**Issue by iampersistent** [vespolina/core#69]
https://github.com/vespolina/VespolinaCore/blob/master/lib/Vespolina/Entity/Order/BaseOrder.php#L268 This should be setPaymentProfile and getPaymentProfile and the parameter on the setter should be a PaymentProfileInterface. Add a reference-one mapping for paymentProfile https://github.com/vespolina/VespolinaOrder/blob/master/lib/Vespolina/Order/Mapping/BaseOrder.mongodb.xml

**Comment by cordoval** [comment]
why it was closed?

**Comment by iampersistent** [comment]
Because it doesn't really make sense to save it there. The transaction needs to be saved with the order and the payment profile is part of the transaction.
